# https://pre-commit.com/hooks.html

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-added-large-files
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports
      exclude: ^.*\b(migrations)\b.*$
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      exclude: ^.*\b(migrations)\b.*$
      # args: [-S]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [ python ]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc"
        ]
